export const initialState = {
  posts: {
    data: [
      // {
      //   id: '1',
      //   title: 'Lorem ipsum',
      //   text: 'A bb ccc dddd eeeee ffffff ggggggg hhhhhhhh.',
      //   pubDate: '2021-12-13',
      //   upDate: '2021-12-27',
      //   email: 'johndoe@example.com',
      //   status: 'closed',
      //   image: 'https://images.pexels.com/photos/5721812/pexels-photo-5721812.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      //   price: '199$',
      //   phone: '123-456-789',
      //   location: 'London',
      // },
      // {
      //   id: '2',
      //   title: 'Ipsum Lorem',
      //   text: 'A bb ccc dddd eeeee ffffff ggggggg hhhhhhhh.',
      //   pubDate: '2021-12-19',
      //   upDate: '2021-12-31',
      //   email: 'janedoe@example.com',
      //   status: 'published',
      //   image: 'https://images.pexels.com/photos/5721814/pexels-photo-5721814.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      //   price: '179$',
      //   phone: '456-789-012',
      //   location: 'Boston',
      // },
      // {
      //   id: '3',
      //   title: 'Lorem lorem',
      //   text: 'A bb ccc dddd eeeee ffffff ggggggg hhhhhhhh.',
      //   pubDate: '2022-01-02',
      //   upDate: '2022-01-03',
      //   email: 'janedoe@example.com',
      //   status: 'published',
      //   image: 'https://images.pexels.com/photos/5721879/pexels-photo-5721879.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      //   price: '169$',
      //   phone: '456-789-012',
      //   location: 'Boston',
      // },
    ],
    loading: {
      active: false,
      error: false,
    },
    post: {},
  },
  users: {
    email: 'user123@example.com',
    type: 'user',
    logged: true,
  },
};
